# Generated by Django 4.2.4 on 2023-08-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_contactdetails"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="contactdetails",
            options={"verbose_name": "Контакты"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(
                help_text="Category description",
                max_length=512,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="address",
            field=models.CharField(max_length=256, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="country",
            field=models.CharField(max_length=64, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="inn",
            field=models.SlugField(max_length=64, verbose_name="ИНН"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="Date and time when the question was created",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="This is a foreign key of the category",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.category",
                verbose_name="Категория товара",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="Date and time when the product was created",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=512, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_preview",
            field=models.ImageField(
                blank=True,
                help_text="Images are here -> images/",
                null=True,
                upload_to="images/",
                verbose_name="Фото товара",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="update_at",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="Date and time when the product was updated",
                verbose_name="Обновлено",
            ),
        ),
    ]
