# Generated by Django 4.2.4 on 2023-08-11 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0003_alter_category_options_alter_contactdetails_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ("create_at",)},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("price",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
