# Generated by Django 4.2.4 on 2023-08-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_feedback_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactdetails",
            options={"verbose_name": "Контакты", "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="inn",
            field=models.CharField(max_length=64, verbose_name="ИНН"),
        ),
    ]
