# Generated by Django 4.2.4 on 2023-08-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_contactdetails_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="Заголовок")),
                ("slug", models.SlugField()),
                ("content", models.CharField(max_length=1024, verbose_name="Контент")),
                (
                    "image_preview",
                    models.ImageField(
                        blank=True,
                        help_text="Images are here -> images/",
                        null=True,
                        upload_to="images/",
                        verbose_name="Изображение",
                    ),
                ),
                ("is_published", models.BooleanField(verbose_name="Опубликовано?")),
                (
                    "views_count",
                    models.PositiveIntegerField(verbose_name="Количество просмотров"),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Date and time when the post was created",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "db_table_comment": "Blog content",
            },
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="country",
            field=models.CharField(max_length=64, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="Date and time when the question was created",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="Date and time when the product was created",
                verbose_name="Дата создания",
            ),
        ),
    ]
