# Generated by Django 4.2.4 on 2023-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_blogarticle_alter_contactdetails_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
