# Generated by Django 4.2.4 on 2023-08-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_blogarticle_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано?"),
        ),
    ]
