# Generated by Django 4.2.4 on 2023-08-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_blogarticle_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
