# Generated by Django 4.2.4 on 2023-08-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_alter_blogarticle_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="slug",
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
    ]
