# Generated by Django 4.2.4 on 2023-08-19 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_fieldstest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FieldsTest",
        ),
    ]
